/* tslint:disable */
/* eslint-disable */
/**
 * SWAIN API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiFilterPayload
 */
export interface ApiFilterPayload {
    /**
     * 
     * @type {Array<object>}
     * @memberof ApiFilterPayload
     */
    expressions?: Array<object>;
}

/**
 * Check if a given object implements the ApiFilterPayload interface.
 */
export function instanceOfApiFilterPayload(value: object): value is ApiFilterPayload {
    return true;
}

export function ApiFilterPayloadFromJSON(json: any): ApiFilterPayload {
    return ApiFilterPayloadFromJSONTyped(json, false);
}

export function ApiFilterPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiFilterPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'expressions': json['expressions'] == null ? undefined : json['expressions'],
    };
}

export function ApiFilterPayloadToJSON(json: any): ApiFilterPayload {
    return ApiFilterPayloadToJSONTyped(json, false);
}

export function ApiFilterPayloadToJSONTyped(value?: ApiFilterPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expressions': value['expressions'],
    };
}

