"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * SWAIN API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfApiFilterPayload = instanceOfApiFilterPayload;
exports.ApiFilterPayloadFromJSON = ApiFilterPayloadFromJSON;
exports.ApiFilterPayloadFromJSONTyped = ApiFilterPayloadFromJSONTyped;
exports.ApiFilterPayloadToJSON = ApiFilterPayloadToJSON;
exports.ApiFilterPayloadToJSONTyped = ApiFilterPayloadToJSONTyped;
/**
 * Check if a given object implements the ApiFilterPayload interface.
 */
function instanceOfApiFilterPayload(value) {
    return true;
}
function ApiFilterPayloadFromJSON(json) {
    return ApiFilterPayloadFromJSONTyped(json, false);
}
function ApiFilterPayloadFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'expressions': json['expressions'] == null ? undefined : json['expressions'],
    };
}
function ApiFilterPayloadToJSON(json) {
    return ApiFilterPayloadToJSONTyped(json, false);
}
function ApiFilterPayloadToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'expressions': value['expressions'],
    };
}
