"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * SWAIN API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfApiModelsResponse = instanceOfApiModelsResponse;
exports.ApiModelsResponseFromJSON = ApiModelsResponseFromJSON;
exports.ApiModelsResponseFromJSONTyped = ApiModelsResponseFromJSONTyped;
exports.ApiModelsResponseToJSON = ApiModelsResponseToJSON;
exports.ApiModelsResponseToJSONTyped = ApiModelsResponseToJSONTyped;
/**
 * Check if a given object implements the ApiModelsResponse interface.
 */
function instanceOfApiModelsResponse(value) {
    return true;
}
function ApiModelsResponseFromJSON(json) {
    return ApiModelsResponseFromJSONTyped(json, false);
}
function ApiModelsResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'models': json['models'] == null ? undefined : json['models'],
    };
}
function ApiModelsResponseToJSON(json) {
    return ApiModelsResponseToJSONTyped(json, false);
}
function ApiModelsResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'models': value['models'],
    };
}
