/* tslint:disable */
/* eslint-disable */
/**
 * SWAIN API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiSuccessResponse
 */
export interface ApiSuccessResponse {
    /**
     * 
     * @type {object}
     * @memberof ApiSuccessResponse
     */
    id?: object;
    /**
     * 
     * @type {string}
     * @memberof ApiSuccessResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiSuccessResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the ApiSuccessResponse interface.
 */
export function instanceOfApiSuccessResponse(value: object): value is ApiSuccessResponse {
    return true;
}

export function ApiSuccessResponseFromJSON(json: any): ApiSuccessResponse {
    return ApiSuccessResponseFromJSONTyped(json, false);
}

export function ApiSuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSuccessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function ApiSuccessResponseToJSON(json: any): ApiSuccessResponse {
    return ApiSuccessResponseToJSONTyped(json, false);
}

export function ApiSuccessResponseToJSONTyped(value?: ApiSuccessResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'message': value['message'],
        'success': value['success'],
    };
}

