"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * SWAIN API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfApiSuccessResponse = instanceOfApiSuccessResponse;
exports.ApiSuccessResponseFromJSON = ApiSuccessResponseFromJSON;
exports.ApiSuccessResponseFromJSONTyped = ApiSuccessResponseFromJSONTyped;
exports.ApiSuccessResponseToJSON = ApiSuccessResponseToJSON;
exports.ApiSuccessResponseToJSONTyped = ApiSuccessResponseToJSONTyped;
/**
 * Check if a given object implements the ApiSuccessResponse interface.
 */
function instanceOfApiSuccessResponse(value) {
    return true;
}
function ApiSuccessResponseFromJSON(json) {
    return ApiSuccessResponseFromJSONTyped(json, false);
}
function ApiSuccessResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}
function ApiSuccessResponseToJSON(json) {
    return ApiSuccessResponseToJSONTyped(json, false);
}
function ApiSuccessResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'message': value['message'],
        'success': value['success'],
    };
}
