/* tslint:disable */
/* eslint-disable */
/**
 * SWAIN API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser } from './GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser';
import {
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSON,
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSONTyped,
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSON,
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSONTyped,
} from './GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser';

/**
 * 
 * @export
 * @interface AuthAuthResult
 */
export interface AuthAuthResult {
    /**
     * 
     * @type {string}
     * @memberof AuthAuthResult
     */
    refreshToken?: string;
    /**
     * Added: Include assigned role names
     * @type {Array<string>}
     * @memberof AuthAuthResult
     */
    roles?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AuthAuthResult
     */
    token?: string;
    /**
     * "local", "github", "google", etc.
     * @type {string}
     * @memberof AuthAuthResult
     */
    type?: string;
    /**
     * 
     * @type {GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser}
     * @memberof AuthAuthResult
     */
    user?: GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser;
}

/**
 * Check if a given object implements the AuthAuthResult interface.
 */
export function instanceOfAuthAuthResult(value: object): value is AuthAuthResult {
    return true;
}

export function AuthAuthResultFromJSON(json: any): AuthAuthResult {
    return AuthAuthResultFromJSONTyped(json, false);
}

export function AuthAuthResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthAuthResult {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'roles': json['roles'] == null ? undefined : json['roles'],
        'token': json['token'] == null ? undefined : json['token'],
        'type': json['type'] == null ? undefined : json['type'],
        'user': json['user'] == null ? undefined : GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSON(json['user']),
    };
}

export function AuthAuthResultToJSON(json: any): AuthAuthResult {
    return AuthAuthResultToJSONTyped(json, false);
}

export function AuthAuthResultToJSONTyped(value?: AuthAuthResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refresh_token': value['refreshToken'],
        'roles': value['roles'],
        'token': value['token'],
        'type': value['type'],
        'user': GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSON(value['user']),
    };
}

