"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * SWAIN API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAuthAuthResult = instanceOfAuthAuthResult;
exports.AuthAuthResultFromJSON = AuthAuthResultFromJSON;
exports.AuthAuthResultFromJSONTyped = AuthAuthResultFromJSONTyped;
exports.AuthAuthResultToJSON = AuthAuthResultToJSON;
exports.AuthAuthResultToJSONTyped = AuthAuthResultToJSONTyped;
var GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser_1 = require("./GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser");
/**
 * Check if a given object implements the AuthAuthResult interface.
 */
function instanceOfAuthAuthResult(value) {
    return true;
}
function AuthAuthResultFromJSON(json) {
    return AuthAuthResultFromJSONTyped(json, false);
}
function AuthAuthResultFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'roles': json['roles'] == null ? undefined : json['roles'],
        'token': json['token'] == null ? undefined : json['token'],
        'type': json['type'] == null ? undefined : json['type'],
        'user': json['user'] == null ? undefined : (0, GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser_1.GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSON)(json['user']),
    };
}
function AuthAuthResultToJSON(json) {
    return AuthAuthResultToJSONTyped(json, false);
}
function AuthAuthResultToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'refresh_token': value['refreshToken'],
        'roles': value['roles'],
        'token': value['token'],
        'type': value['type'],
        'user': (0, GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser_1.GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSON)(value['user']),
    };
}
