"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * SWAIN API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAuthLoginRequest = instanceOfAuthLoginRequest;
exports.AuthLoginRequestFromJSON = AuthLoginRequestFromJSON;
exports.AuthLoginRequestFromJSONTyped = AuthLoginRequestFromJSONTyped;
exports.AuthLoginRequestToJSON = AuthLoginRequestToJSON;
exports.AuthLoginRequestToJSONTyped = AuthLoginRequestToJSONTyped;
/**
 * Check if a given object implements the AuthLoginRequest interface.
 */
function instanceOfAuthLoginRequest(value) {
    return true;
}
function AuthLoginRequestFromJSON(json) {
    return AuthLoginRequestFromJSONTyped(json, false);
}
function AuthLoginRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'password': json['password'] == null ? undefined : json['password'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}
function AuthLoginRequestToJSON(json) {
    return AuthLoginRequestToJSONTyped(json, false);
}
function AuthLoginRequestToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'password': value['password'],
        'username': value['username'],
    };
}
