/* tslint:disable */
/* eslint-disable */
/**
 * SWAIN API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermission } from './GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermission';
import {
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermissionFromJSON,
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermissionFromJSONTyped,
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermissionToJSON,
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermissionToJSONTyped,
} from './GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermission';
import type { GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser } from './GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser';
import {
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSON,
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSONTyped,
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSON,
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSONTyped,
} from './GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser';

/**
 * 
 * @export
 * @interface GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole
 */
export interface GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole {
    /**
     * 
     * @type {string}
     * @memberof GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole
     */
    id?: number;
    /**
     * Role name must be unique
     * @type {string}
     * @memberof GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole
     */
    name?: string;
    /**
     * 
     * @type {Array<GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermission>}
     * @memberof GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole
     */
    permissions?: Array<GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermission>;
    /**
     * 
     * @type {string}
     * @memberof GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole
     */
    updatedAt?: string;
    /**
     * 
     * @type {Array<GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser>}
     * @memberof GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole
     */
    users?: Array<GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser>;
}

/**
 * Check if a given object implements the GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole interface.
 */
export function instanceOfGithubComTakifouhalCrudsqlPkgInternalAuthModelsRole(value: object): value is GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole {
    return true;
}

export function GithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleFromJSON(json: any): GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole {
    return GithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleFromJSONTyped(json, false);
}

export function GithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'permissions': json['permissions'] == null ? undefined : ((json['permissions'] as Array<any>).map(GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermissionFromJSON)),
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSON)),
    };
}

export function GithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleToJSON(json: any): GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole {
    return GithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleToJSONTyped(json, false);
}

export function GithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleToJSONTyped(value?: GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'permissions': value['permissions'] == null ? undefined : ((value['permissions'] as Array<any>).map(GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermissionToJSON)),
        'updated_at': value['updatedAt'],
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSON)),
    };
}

