/* tslint:disable */
/* eslint-disable */
/**
 * SWAIN API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole } from './GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole';
import {
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleFromJSON,
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleFromJSONTyped,
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleToJSON,
    GithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleToJSONTyped,
} from './GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole';

/**
 * 
 * @export
 * @interface GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser
 */
export interface GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser
     */
    additionalData?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser
     */
    anonymous?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser
     */
    email?: string;
    /**
     * 
     * @type {number}
     * @memberof GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser
     */
    isActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser
     */
    lastLogin?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser
     */
    name?: string;
    /**
     * 
     * @type {Array<GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole>}
     * @memberof GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser
     */
    roles?: Array<GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole>;
}

/**
 * Check if a given object implements the GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser interface.
 */
export function instanceOfGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser(value: object): value is GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser {
    return true;
}

export function GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSON(json: any): GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser {
    return GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSONTyped(json, false);
}

export function GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalData': json['additional_data'] == null ? undefined : json['additional_data'],
        'anonymous': json['anonymous'] == null ? undefined : json['anonymous'],
        'email': json['email'] == null ? undefined : json['email'],
        'id': json['id'] == null ? undefined : json['id'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'lastLogin': json['last_login'] == null ? undefined : json['last_login'],
        'name': json['name'] == null ? undefined : json['name'],
        'roles': json['roles'] == null ? undefined : ((json['roles'] as Array<any>).map(GithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleFromJSON)),
    };
}

export function GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSON(json: any): GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser {
    return GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSONTyped(json, false);
}

export function GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSONTyped(value?: GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additional_data': value['additionalData'],
        'anonymous': value['anonymous'],
        'email': value['email'],
        'id': value['id'],
        'is_active': value['isActive'],
        'last_login': value['lastLogin'],
        'name': value['name'],
        'roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(GithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleToJSON)),
    };
}

