"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * SWAIN API
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser = instanceOfGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser;
exports.GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSON = GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSON;
exports.GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSONTyped = GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSONTyped;
exports.GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSON = GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSON;
exports.GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSONTyped = GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSONTyped;
var GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole_1 = require("./GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole");
/**
 * Check if a given object implements the GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser interface.
 */
function instanceOfGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser(value) {
    return true;
}
function GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSON(json) {
    return GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSONTyped(json, false);
}
function GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'additionalData': json['additional_data'] == null ? undefined : json['additional_data'],
        'anonymous': json['anonymous'] == null ? undefined : json['anonymous'],
        'email': json['email'] == null ? undefined : json['email'],
        'id': json['id'] == null ? undefined : json['id'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'lastLogin': json['last_login'] == null ? undefined : json['last_login'],
        'name': json['name'] == null ? undefined : json['name'],
        'roles': json['roles'] == null ? undefined : (json['roles'].map(GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole_1.GithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleFromJSON)),
    };
}
function GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSON(json) {
    return GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSONTyped(json, false);
}
function GithubComTakifouhalCrudsqlPkgInternalAuthModelsUserToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'additional_data': value['additionalData'],
        'anonymous': value['anonymous'],
        'email': value['email'],
        'id': value['id'],
        'is_active': value['isActive'],
        'last_login': value['lastLogin'],
        'name': value['name'],
        'roles': value['roles'] == null ? undefined : (value['roles'].map(GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole_1.GithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleToJSON)),
    };
}
